import React, { useState, useEffect, useRef } from 'react';
import Navbar from '../components/Navbar';
import { ArrowLeft, Loader, CheckCircle, XCircle, AlertCircle, TrendingUp, UploadCloud } from 'lucide-react';
import { Link } from 'react-router-dom';
import './ATSEvaluation.css';

const ATSEvaluation = () => {
  const [internships, setInternships] = useState([]);
  const [selectedInternshipTerm, setSelectedInternshipTerm] = useState('');
  const [resumeText, setResumeText] = useState("");
  const [uploadedFilename, setUploadedFilename] = useState("");
  
  const [loading, setLoading] = useState(false);
  const [uploading, setUploading] = useState(false);
  const [results, setResults] = useState(null);
  const [error, setError] = useState(null);
  const fileInputRef = useRef(null);

  // Fetch lightweight internships for dropdown
  useEffect(() => {
    const fetchInternships = async () => {
      try {
        const res = await fetch('http://localhost:8000/internships/light');
        if (!res.ok) throw new Error("Failed to fetch internship list");
        const data = await res.json();
        setInternships(data);
      } catch (err) {
        setError("Error loading internships: " + err.message);
      }
    };
    fetchInternships();
  }, []);

  const handleFileUpload = async (e) => {
    const file = e.target.files[0];
    if (!file) return;

    setUploading(true);
    setError(null);
    const formData = new FormData();
    formData.append("file", file);

    try {
      const res = await fetch('http://localhost:8000/extract_pdf', {
        method: 'POST',
        body: formData
      });
      if (!res.ok) throw new Error("Failed to parse PDF backend configuration");
      const data = await res.json();
      if (data.error) throw new Error(data.error);
      
      if (!data.extracted_text || data.extracted_text.trim() === "") {
         setResumeText("🚨 PARSING ERROR: The backend could not extract any readable text from this document. \n\nThis usually means your PDF is an image-based scan (like those generated by html2pdf.js), rather than a document containing native vector text.\n\nMost real-world ATS systems will instantly reject these types of resumes because they cannot parse the words. Please upload a structured text PDF, or paste your raw text directly into this editor.");
      } else {
         setResumeText(data.extracted_text);
      }
      setUploadedFilename(file.name);
    } catch (err) {
      setError("Network or Server Error: " + err.message);
    } finally {
      setUploading(false);
      e.target.value = null; // Reset input so same file can be selected again
    }
  };

  const handleEvaluate = async () => {
    // Attempt to map the typed term back to an internship ID
    const target = internships.find(i => i.title === selectedInternshipTerm);
    const internshipId = target ? target.id : selectedInternshipTerm;

    if (!internshipId || !resumeText) return;
    
    setLoading(true);
    setError(null);
    try {
      const res = await fetch('http://localhost:8000/evaluate_ats', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          resume_text: resumeText,
          internship_id: String(internshipId),
          user_skills: [] // Backend now dynamically extracts from resume_text
        })
      });
      
      if (!res.ok) throw new Error("Evaluation failed.");
      
      const data = await res.json();
      if (data.error) throw new Error(data.error);
      
      setResults(data);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="dashboard-layout animate-fade-in">
      <Navbar />
      
      <div className="dashboard-container" style={{ padding: '2rem' }}>
        <Link to="/dashboard" className="back-link">
          <ArrowLeft size={16} /> Back to Dashboard
        </Link>
        
        <div className="ats-header-area">
          <h1>ATS Resume Evaluation</h1>
          <p>Test your resume against real Semantic ML and Keyword screening filters.</p>
        </div>

        <div className="ats-grid">
          {/* LEFT: INPUTS */}
          <div className="ats-inputs-section">
            <div className="input-group">
              <label>Select Target Internship</label>
              <input 
                type="text" 
                value={selectedInternshipTerm} 
                onChange={(e) => setSelectedInternshipTerm(e.target.value)}
                placeholder="Type to search roles..."
                className="ats-dropdown"
                list="internship-options"
              />
              <datalist id="internship-options">
                {internships.map(i => (
                  <option key={i.id} value={i.title} />
                ))}
              </datalist>
            </div>
            
            <div className="input-group">
              <label style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <span>Resume Text Editor {uploadedFilename && <span style={{fontSize: '0.8rem', color: '#34d399', fontWeight: 'normal', marginLeft: '8px'}}>({uploadedFilename} loaded)</span>}</span>
                <button 
                  className="upload-trigger-btn"
                  onClick={() => fileInputRef.current.click()}
                  disabled={uploading}
                >
                  {uploading ? <Loader className="animate-spin" size={14}/> : <UploadCloud size={14}/>}
                  {uploading ? "Parsing..." : "Upload PDF"}
                </button>
              </label>
              
              <input 
                type="file" 
                accept=".pdf" 
                ref={fileInputRef} 
                style={{ display: 'none' }} 
                onChange={handleFileUpload} 
              />
              
              <textarea 
                className="resume-textarea"
                rows={15}
                value={resumeText}
                onChange={(e) => setResumeText(e.target.value)}
                placeholder="Paste your raw resume text here, or click Upload PDF to auto-fill..."
              ></textarea>
            </div>
            
            <button 
              className="evaluate-btn" 
              onClick={handleEvaluate}
              disabled={loading || !selectedInternshipTerm || !resumeText}
            >
              {loading ? <Loader className="animate-spin" size={18} /> : "Run ATS Evaluation"}
            </button>
            {error && <p className="error-text">{error}</p>}
          </div>

          {/* RIGHT: RESULTS */}
          <div className="ats-results-section">
            {results ? (
              <div className="results-card animate-fade-in">
                
                {/* Score Indicator */}
                <div className="score-header">
                  <div className={`score-circle ${results.score >= 80 ? 'high' : results.score >= 50 ? 'med' : 'low'}`}>
                    <span className="score-val">{results.score}</span>
                    <span className="score-max">/ 100</span>
                  </div>
                  <div className="score-details">
                    <h3>Compatibility Score</h3>
                    <p>Semantic Similarity: <strong>{results.semantic_score}</strong></p>
                    <p>Keyword Match: <strong>{results.keyword_component || "N/A"}</strong></p>
                  </div>
                </div>

                <hr className="divider" />

                {/* Suggestions */}
                <div className="suggestions-section">
                  <h4><TrendingUp size={16}/> Improvement Suggestions</h4>
                  <ul>
                    {results.suggestions.map((s, idx) => (
                      <li key={idx}><AlertCircle size={14} style={{display:'inline', marginRight:'6px', color:'var(--primary-color)'}}/>{s}</li>
                    ))}
                  </ul>
                </div>

                {/* Skills Analysis */}
                <div className="skills-analysis">
                  <div className="skill-box">
                    <h4><CheckCircle size={16} color="#34d399"/> Matched Skills</h4>
                    <div className="pill-container">
                      {results.matched_skills.length > 0 ? results.matched_skills.map((s, i) => (
                        <span key={i} className="skill-pill match">{s}</span>
                      )) : <span className="no-data">None found</span>}
                    </div>
                  </div>
                  
                  <div className="skill-box">
                    <h4><XCircle size={16} color="#f87171"/> Missing Keywords</h4>
                    <div className="pill-container">
                      {results.missing_skills.length > 0 ? results.missing_skills.map((s, i) => (
                        <span key={i} className="skill-pill missing">{s}</span>
                      )) : <span className="no-data">No missing skills targeted.</span>}
                    </div>
                  </div>
                </div>

              </div>
            ) : (
              <div className="empty-results">
                <AlertCircle size={48} />
                <p>Select an internship and click Evaluate to see your ATS score.</p>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default ATSEvaluation;
